// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/aperturerobotics/entitygraph/controller/config.proto (package entitygraph.controller, syntax proto3)
/* eslint-disable */

import type { MessageType, PartialFieldInfo } from '@aptre/protobuf-es-lite'
import { createMessageType } from '@aptre/protobuf-es-lite'

export const protobufPackage = 'entitygraph.controller'

/**
 * Config is the entity graph aggregation controller config.
 *
 * @generated from message entitygraph.controller.Config
 */
export interface Config {}

// Config contains the message type declaration for Config.
export const Config: MessageType<Config> = createMessageType({
  typeName: 'entitygraph.controller.Config',
  fields: [] as readonly PartialFieldInfo[],
  packedByDefault: true,
})
